### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by codingpixi** [shadows-tiy/shadows#67]
This component will dynamically display list of available developers/students via materialize card. Each card will display the following user information
- name
- avatar
- availability
- tech stack

I built this component on Friday (6/16). I will work to import it into App.js to make it visible for testing.

**Comment by ddsheard** [comment]
I built this component on Friday. I will work to import it into App.js to make it visible for testing.

**Comment by codingpixi** [comment]
I am now pushing the Github name, login, and name into Firebase. I updated the ShadowList.js file to pull from Firebase. This list is now dynamically displaying the specific type.
